version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: postgres-container
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
volumes:
    .postgres-data: